import js from '@eslint/js'
import prettier from 'eslint-config-prettier'
import reactHooks from 'eslint-plugin-react-hooks'
import tseslint from 'typescript-eslint'

/**
 * Shared lint rules.
 *
 * Deliberately light. Formatting is Prettier's job (eslint-config-prettier
 * turns off anything that would fight it), so these rules only cover things
 * that are actually bugs or that this codebase has taken a position on.
 */
export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/.turbo/**',
      '**/coverage/**',
      // Generated by Prisma — not ours to lint.
      'apps/api/src/generated/**',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    rules: {
      // Unused args are fine when prefixed with _, which we use for the
      // deliberately-ignored parameters Nest's interfaces require.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      // `any` defeats the shared-types guarantee between the API and the web app.
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
    },
  },

  // Seed and tooling scripts are meant to print to the console.
  {
    files: ['apps/api/prisma/**/*.ts', 'scripts/**/*.mjs', '**/*.config.{ts,mjs,js}'],
    rules: { 'no-console': 'off' },
  },

  /*
   * NestJS resolves constructor dependencies from decorator metadata, which
   * only exists for runtime imports. `import type { PrismaService }` erases the
   * class and dependency injection then fails at runtime — so the rule is off
   * for the API's source.
   */
  {
    files: ['apps/api/src/**/*.ts'],
    rules: { '@typescript-eslint/consistent-type-imports': 'off' },
  },

  // React rules, for the web app and the design system.
  {
    files: ['apps/web/**/*.{ts,tsx}', 'packages/ui/**/*.{ts,tsx}'],
    plugins: { 'react-hooks': reactHooks },
    rules: {
      ...reactHooks.configs.recommended.rules,
    },
  },

  prettier,
)
