import js from '@eslint/js'
import prettier from 'eslint-config-prettier'
import reactHooks from 'eslint-plugin-react-hooks'
import tseslint from 'typescript-eslint'

/**
 * Shared lint rules.
 *
 * Deliberately light. Formatting is Prettier's job (eslint-config-prettier
 * turns off anything that would fight it), so these rules only cover things
 * that are actually bugs or that this codebase has taken a position on.
 */
export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/.turbo/**',
      '**/coverage/**',
      // Generated by Prisma — not ours to lint.
      'apps/api/src/generated/**',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    rules: {
      // Unused args are fine when prefixed with _, which we use for the
      // deliberately-ignored parameters Nest's interfaces require.
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      // `any` defeats the shared-types guarantee between the API and the web app.
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/consistent-type-imports': [
        'error',
        { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
      ],
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
    },
  },

  // Seed and tooling scripts are meant to print to the console.
  {
    files: ['apps/api/prisma/**/*.ts', 'scripts/**/*.mjs', '**/*.config.{ts,mjs,js}'],
    rules: { 'no-console': 'off' },
  },

  // Jest's own plumbing runs in CommonJS under Node, so it needs the Node
  // globals the browser-shaped default config does not provide.
  {
    files: ['**/jest.config.js', '**/jest.setup.js'],
    languageOptions: {
      globals: { module: 'writable', process: 'readonly', require: 'readonly', __dirname: 'readonly' },
    },
  },

  /*
   * Test doubles stand in for Prisma's generated client, whose argument types
   * are enormous generic unions. Reproducing them would make a fake harder to
   * read than the thing it replaces, and the compiler still checks every call
   * the service makes against the real client.
   */
  {
    files: ['**/*.spec.ts'],
    rules: { '@typescript-eslint/no-explicit-any': 'off' },
  },

  /*
   * NestJS resolves constructor dependencies from decorator metadata, which
   * only exists for runtime imports. `import type { PrismaService }` erases the
   * class and dependency injection then fails at runtime — so the rule is off
   * for the API's source.
   */
  {
    files: ['apps/api/src/**/*.ts'],
    rules: { '@typescript-eslint/consistent-type-imports': 'off' },
  },

  // React rules, for the web app and the design system.
  {
    files: ['apps/web/**/*.{ts,tsx}', 'packages/ui/**/*.{ts,tsx}'],
    plugins: { 'react-hooks': reactHooks },
    rules: {
      ...reactHooks.configs.recommended.rules,
    },
  },

  /*
   * ARCHITECTURE RULE 1 — tenant modules never touch PrismaService directly.
   *
   * PrismaService uses the owner connection, which BYPASSES Row-Level Security.
   * One direct import in one service is a cross-tenant leak that no test would
   * notice, because the query looks perfectly correct.
   *
   * Tenant data goes through TenantPrismaService, which runs inside a
   * transaction with app.company_id set. The exceptions below are the
   * infrastructure that has to hold the raw client, plus platform-owner
   * surfaces that are tenant-wide by definition.
   */
  {
    files: ['apps/api/src/**/*.ts'],
    ignores: [
      'apps/api/src/common/prisma/**',
      // TenantPrismaService wraps the raw client; it is the one file that must
      // hold it. The rest of tenancy/ goes through runPreTenant like everyone
      // else, so the blanket exception it used to have is gone.
      'apps/api/src/tenancy/tenant-prisma.service.ts',
      // The two auth tables without a companyId — identities and refresh
      // tokens — carry no tenant to scope by. Everything else in auth/ that
      // touches a tenant table now uses runPreTenant.
      'apps/api/src/auth/token.service.ts',
      'apps/api/src/auth/providers/password.provider.ts',
      // Health checks must answer before, and independently of, any tenant.
      'apps/api/src/health/**',
      'apps/api/src/generated/**',
    ],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/common/prisma/prisma.service', '**/prisma/prisma.service'],
              message:
                'Tenant modules must not use PrismaService — it bypasses Row-Level Security. Use TenantPrismaService. See docs/ARCHITECTURE.md.',
            },
          ],
        },
      ],
    },
  },

  /*
   * ARCHITECTURE RULE 2 — controllers hold no business logic.
   *
   * A controller translates HTTP to a service call and back. Keeping it that
   * thin is what lets the mobile app, the public API and background jobs reuse
   * the same services instead of re-implementing the rules.
   */
  {
    files: ['apps/api/src/**/*.controller.ts'],
    rules: {
      'max-lines-per-function': [
        'warn',
        { max: 30, skipComments: true, skipBlankLines: true },
      ],
    },
  },

  prettier,
)
