import { type DrugSchedule, type MedicineForm } from '../../src/generated/prisma/enums'

/**
 * A realistic slice of the Indian pharmacy catalogue.
 *
 * Chosen to exercise the parts of the system that are easy to get wrong:
 *   - several brands sharing one composition, so price comparison is testable
 *   - all four GST rates
 *   - Schedule NONE, H and H1 entries
 *   - one Schedule X entry, which must stay invisible everywhere
 */

export interface SeedMedicine {
  name: string
  brand: string
  composition: string
  form: MedicineForm
  strength?: string
  packSize?: string
  manufacturer?: string
  hsnCode: string
  gstRate: number
  schedule: DrugSchedule
  isPrescriptionRequired?: boolean
}

export const seedMedicines: SeedMedicine[] = [
  // --- Analgesics / antipyretics: four brands, one salt ---
  {
    name: 'Crocin Advance',
    brand: 'Crocin',
    composition: 'Paracetamol 500mg',
    form: 'TABLET',
    strength: '500mg',
    packSize: '15 tablets',
    manufacturer: 'GSK',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'NONE',
  },
  {
    name: 'Dolo 650',
    brand: 'Dolo',
    composition: 'Paracetamol 650mg',
    form: 'TABLET',
    strength: '650mg',
    packSize: '15 tablets',
    manufacturer: 'Micro Labs',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'NONE',
  },
  {
    name: 'Calpol 500',
    brand: 'Calpol',
    composition: 'Paracetamol 500mg',
    form: 'TABLET',
    strength: '500mg',
    packSize: '15 tablets',
    manufacturer: 'GSK',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'NONE',
  },
  {
    name: 'Paracip 500',
    brand: 'Paracip',
    composition: 'Paracetamol 500mg',
    form: 'TABLET',
    strength: '500mg',
    packSize: '10 tablets',
    manufacturer: 'Cipla',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'NONE',
  },
  {
    name: 'Combiflam',
    brand: 'Combiflam',
    composition: 'Ibuprofen 400mg + Paracetamol 325mg',
    form: 'TABLET',
    strength: '400mg+325mg',
    packSize: '20 tablets',
    manufacturer: 'Sanofi',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'NONE',
  },
  {
    name: 'Brufen 400',
    brand: 'Brufen',
    composition: 'Ibuprofen 400mg',
    form: 'TABLET',
    strength: '400mg',
    packSize: '15 tablets',
    manufacturer: 'Abbott',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'NONE',
  },
  {
    name: 'Aspirin 75',
    brand: 'Ecosprin',
    composition: 'Aspirin 75mg',
    form: 'TABLET',
    strength: '75mg',
    packSize: '14 tablets',
    manufacturer: 'USV',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'NONE',
  },
  {
    name: 'Meftal Spas',
    brand: 'Meftal',
    composition: 'Mefenamic Acid 250mg + Dicyclomine 10mg',
    form: 'TABLET',
    strength: '250mg+10mg',
    packSize: '10 tablets',
    manufacturer: 'Blue Cross',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'H',
  },

  // --- Antibiotics: Schedule H, prescription required ---
  {
    name: 'Augmentin 625 Duo',
    brand: 'Augmentin',
    composition: 'Amoxicillin 500mg + Clavulanic Acid 125mg',
    form: 'TABLET',
    strength: '625mg',
    packSize: '10 tablets',
    manufacturer: 'GSK',
    hsnCode: '30042019',
    gstRate: 12,
    schedule: 'H',
    isPrescriptionRequired: true,
  },
  {
    name: 'Azithral 500',
    brand: 'Azithral',
    composition: 'Azithromycin 500mg',
    form: 'TABLET',
    strength: '500mg',
    packSize: '5 tablets',
    manufacturer: 'Alembic',
    hsnCode: '30042019',
    gstRate: 12,
    schedule: 'H',
    isPrescriptionRequired: true,
  },
  {
    name: 'Azee 500',
    brand: 'Azee',
    composition: 'Azithromycin 500mg',
    form: 'TABLET',
    strength: '500mg',
    packSize: '3 tablets',
    manufacturer: 'Cipla',
    hsnCode: '30042019',
    gstRate: 12,
    schedule: 'H',
    isPrescriptionRequired: true,
  },
  {
    name: 'Taxim-O 200',
    brand: 'Taxim-O',
    composition: 'Cefixime 200mg',
    form: 'TABLET',
    strength: '200mg',
    packSize: '10 tablets',
    manufacturer: 'Alkem',
    hsnCode: '30042019',
    gstRate: 12,
    schedule: 'H',
    isPrescriptionRequired: true,
  },
  {
    name: 'Ciplox 500',
    brand: 'Ciplox',
    composition: 'Ciprofloxacin 500mg',
    form: 'TABLET',
    strength: '500mg',
    packSize: '10 tablets',
    manufacturer: 'Cipla',
    hsnCode: '30042019',
    gstRate: 12,
    schedule: 'H',
    isPrescriptionRequired: true,
  },
  {
    name: 'Monocef 1g Injection',
    brand: 'Monocef',
    composition: 'Ceftriaxone 1000mg',
    form: 'INJECTION',
    strength: '1g',
    packSize: '1 vial',
    manufacturer: 'Aristo',
    hsnCode: '30042019',
    gstRate: 12,
    schedule: 'H',
    isPrescriptionRequired: true,
  },
  {
    name: 'Metrogyl 400',
    brand: 'Metrogyl',
    composition: 'Metronidazole 400mg',
    form: 'TABLET',
    strength: '400mg',
    packSize: '15 tablets',
    manufacturer: 'JB Chemicals',
    hsnCode: '30042019',
    gstRate: 12,
    schedule: 'H',
    isPrescriptionRequired: true,
  },
  {
    name: 'Levoflox 500',
    brand: 'Levoflox',
    composition: 'Levofloxacin 500mg',
    form: 'TABLET',
    strength: '500mg',
    packSize: '5 tablets',
    manufacturer: 'Cipla',
    hsnCode: '30042019',
    gstRate: 12,
    schedule: 'H1',
    isPrescriptionRequired: true,
  },

  // --- Gastro ---
  {
    name: 'Pan 40',
    brand: 'Pan',
    composition: 'Pantoprazole 40mg',
    form: 'TABLET',
    strength: '40mg',
    packSize: '15 tablets',
    manufacturer: 'Alkem',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'H',
  },
  {
    name: 'Pantocid 40',
    brand: 'Pantocid',
    composition: 'Pantoprazole 40mg',
    form: 'TABLET',
    strength: '40mg',
    packSize: '15 tablets',
    manufacturer: 'Sun Pharma',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'H',
  },
  {
    name: 'Omez 20',
    brand: 'Omez',
    composition: 'Omeprazole 20mg',
    form: 'CAPSULE',
    strength: '20mg',
    packSize: '20 capsules',
    manufacturer: 'Dr Reddys',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'H',
  },
  {
    name: 'Rantac 150',
    brand: 'Rantac',
    composition: 'Ranitidine 150mg',
    form: 'TABLET',
    strength: '150mg',
    packSize: '30 tablets',
    manufacturer: 'JB Chemicals',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'H',
  },
  {
    name: 'Digene Gel',
    brand: 'Digene',
    composition: 'Magnesium Hydroxide + Aluminium Hydroxide + Simethicone',
    form: 'SYRUP',
    packSize: '200ml',
    manufacturer: 'Abbott',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'NONE',
  },
  {
    name: 'Ondem 4',
    brand: 'Ondem',
    composition: 'Ondansetron 4mg',
    form: 'TABLET',
    strength: '4mg',
    packSize: '10 tablets',
    manufacturer: 'Alkem',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'H',
  },
  {
    name: 'Eldoper',
    brand: 'Eldoper',
    composition: 'Loperamide 2mg',
    form: 'CAPSULE',
    strength: '2mg',
    packSize: '10 capsules',
    manufacturer: 'Micro Labs',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'H',
  },

  // --- Diabetes / cardiac ---
  {
    name: 'Glycomet 500 SR',
    brand: 'Glycomet',
    composition: 'Metformin 500mg',
    form: 'TABLET',
    strength: '500mg',
    packSize: '20 tablets',
    manufacturer: 'USV',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'H',
  },
  {
    name: 'Glucophage 500',
    brand: 'Glucophage',
    composition: 'Metformin 500mg',
    form: 'TABLET',
    strength: '500mg',
    packSize: '20 tablets',
    manufacturer: 'Merck',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'H',
  },
  {
    name: 'Januvia 100',
    brand: 'Januvia',
    composition: 'Sitagliptin 100mg',
    form: 'TABLET',
    strength: '100mg',
    packSize: '7 tablets',
    manufacturer: 'MSD',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'H',
  },
  {
    name: 'Telma 40',
    brand: 'Telma',
    composition: 'Telmisartan 40mg',
    form: 'TABLET',
    strength: '40mg',
    packSize: '15 tablets',
    manufacturer: 'Glenmark',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'H',
  },
  {
    name: 'Amlokind 5',
    brand: 'Amlokind',
    composition: 'Amlodipine 5mg',
    form: 'TABLET',
    strength: '5mg',
    packSize: '15 tablets',
    manufacturer: 'Mankind',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'H',
  },
  {
    name: 'Atorva 10',
    brand: 'Atorva',
    composition: 'Atorvastatin 10mg',
    form: 'TABLET',
    strength: '10mg',
    packSize: '15 tablets',
    manufacturer: 'Zydus',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'H',
  },
  {
    name: 'Clopilet A 75',
    brand: 'Clopilet',
    composition: 'Clopidogrel 75mg + Aspirin 75mg',
    form: 'TABLET',
    strength: '75mg+75mg',
    packSize: '10 tablets',
    manufacturer: 'Sun Pharma',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'H',
  },

  // --- Respiratory / allergy ---
  {
    name: 'Montair LC',
    brand: 'Montair',
    composition: 'Montelukast 10mg + Levocetirizine 5mg',
    form: 'TABLET',
    strength: '10mg+5mg',
    packSize: '10 tablets',
    manufacturer: 'Cipla',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'H',
  },
  {
    name: 'Allegra 120',
    brand: 'Allegra',
    composition: 'Fexofenadine 120mg',
    form: 'TABLET',
    strength: '120mg',
    packSize: '10 tablets',
    manufacturer: 'Sanofi',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'NONE',
  },
  {
    name: 'Cetzine 10',
    brand: 'Cetzine',
    composition: 'Cetirizine 10mg',
    form: 'TABLET',
    strength: '10mg',
    packSize: '10 tablets',
    manufacturer: 'GSK',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'NONE',
  },
  {
    name: 'Asthalin Inhaler',
    brand: 'Asthalin',
    composition: 'Salbutamol 100mcg',
    form: 'INHALER',
    strength: '100mcg',
    packSize: '200 doses',
    manufacturer: 'Cipla',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'H',
  },
  {
    name: 'Foracort 200 Inhaler',
    brand: 'Foracort',
    composition: 'Formoterol 6mcg + Budesonide 200mcg',
    form: 'INHALER',
    packSize: '120 doses',
    manufacturer: 'Cipla',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'H',
  },
  {
    name: 'Ascoril LS Syrup',
    brand: 'Ascoril',
    composition: 'Ambroxol + Levosalbutamol + Guaifenesin',
    form: 'SYRUP',
    packSize: '100ml',
    manufacturer: 'Glenmark',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'H',
  },

  // --- Vitamins and supplements: 5% and 18% GST bands ---
  {
    name: 'Shelcal 500',
    brand: 'Shelcal',
    composition: 'Calcium Carbonate 500mg + Vitamin D3 250IU',
    form: 'TABLET',
    packSize: '15 tablets',
    manufacturer: 'Torrent',
    hsnCode: '30045020',
    gstRate: 12,
    schedule: 'NONE',
  },
  {
    name: 'Becosules',
    brand: 'Becosules',
    composition: 'Vitamin B Complex + Vitamin C',
    form: 'CAPSULE',
    packSize: '20 capsules',
    manufacturer: 'Pfizer',
    hsnCode: '30045020',
    gstRate: 12,
    schedule: 'NONE',
  },
  {
    name: 'Zincovit',
    brand: 'Zincovit',
    composition: 'Multivitamin + Multimineral + Zinc',
    form: 'TABLET',
    packSize: '15 tablets',
    manufacturer: 'Apex',
    hsnCode: '30045020',
    gstRate: 12,
    schedule: 'NONE',
  },
  {
    name: 'Neurobion Forte',
    brand: 'Neurobion',
    composition: 'Vitamin B1 + B6 + B12',
    form: 'TABLET',
    packSize: '30 tablets',
    manufacturer: 'Merck',
    hsnCode: '30045020',
    gstRate: 12,
    schedule: 'NONE',
  },
  {
    name: 'Limcee 500',
    brand: 'Limcee',
    composition: 'Vitamin C 500mg',
    form: 'TABLET',
    strength: '500mg',
    packSize: '15 tablets',
    manufacturer: 'Abbott',
    hsnCode: '30045020',
    gstRate: 5,
    schedule: 'NONE',
  },
  {
    name: 'ORS Powder',
    brand: 'Electral',
    composition: 'Oral Rehydration Salts',
    form: 'POWDER',
    packSize: '21.8g sachet',
    manufacturer: 'FDC',
    hsnCode: '30049099',
    gstRate: 5,
    schedule: 'NONE',
  },

  // --- Topicals and devices ---
  {
    name: 'Betadine Ointment',
    brand: 'Betadine',
    composition: 'Povidone Iodine 5%',
    form: 'OINTMENT',
    packSize: '20g',
    manufacturer: 'Win Medicare',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'NONE',
  },
  {
    name: 'Soframycin Cream',
    brand: 'Soframycin',
    composition: 'Framycetin 1%',
    form: 'CREAM',
    packSize: '30g',
    manufacturer: 'Sanofi',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'H',
  },
  {
    name: 'Volini Gel',
    brand: 'Volini',
    composition: 'Diclofenac + Methyl Salicylate + Menthol',
    form: 'GEL',
    packSize: '30g',
    manufacturer: 'Sun Pharma',
    hsnCode: '30049099',
    gstRate: 18,
    schedule: 'NONE',
  },
  {
    name: 'Moov Spray',
    brand: 'Moov',
    composition: 'Diclofenac Diethylamine',
    form: 'SPRAY',
    packSize: '80g',
    manufacturer: 'Reckitt',
    hsnCode: '30049099',
    gstRate: 18,
    schedule: 'NONE',
  },
  {
    name: 'Dettol Antiseptic Liquid',
    brand: 'Dettol',
    composition: 'Chloroxylenol 4.8%',
    form: 'OTHER',
    packSize: '250ml',
    manufacturer: 'Reckitt',
    hsnCode: '38089400',
    gstRate: 18,
    schedule: 'NONE',
  },

  // --- Eye and ENT ---
  {
    name: 'Refresh Tears',
    brand: 'Refresh',
    composition: 'Carboxymethylcellulose 0.5%',
    form: 'DROPS',
    packSize: '10ml',
    manufacturer: 'Allergan',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'NONE',
  },
  {
    name: 'Otek AC Drops',
    brand: 'Otek',
    composition: 'Clotrimazole + Beclomethasone + Lignocaine',
    form: 'DROPS',
    packSize: '5ml',
    manufacturer: 'Zydus',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'H',
  },
  {
    name: 'Nasivion Nasal Drops',
    brand: 'Nasivion',
    composition: 'Oxymetazoline 0.05%',
    form: 'DROPS',
    packSize: '10ml',
    manufacturer: 'Merck',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'NONE',
  },

  // --- Thyroid ---
  {
    name: 'Thyronorm 50mcg',
    brand: 'Thyronorm',
    composition: 'Thyroxine Sodium 50mcg',
    form: 'TABLET',
    strength: '50mcg',
    packSize: '120 tablets',
    manufacturer: 'Abbott',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'H',
  },
  {
    name: 'Eltroxin 100mcg',
    brand: 'Eltroxin',
    composition: 'Thyroxine Sodium 100mcg',
    form: 'TABLET',
    strength: '100mcg',
    packSize: '100 tablets',
    manufacturer: 'GSK',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'H',
  },

  /**
   * Schedule X — deliberately seeded so we can prove the block works.
   * This must never appear in retailer search, and no distributor may list it.
   * Any change that makes this visible is a compliance bug, not a UI bug.
   */
  {
    name: 'Alprax 0.5',
    brand: 'Alprax',
    composition: 'Alprazolam 0.5mg',
    form: 'TABLET',
    strength: '0.5mg',
    packSize: '15 tablets',
    manufacturer: 'Torrent',
    hsnCode: '30049099',
    gstRate: 12,
    schedule: 'X',
    isPrescriptionRequired: true,
  },
]
